import { current } from '@reduxjs/toolkit'
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchCityWeather } from './forecastAPI';//this is some axios stuff

const initialState = {
  forecasts: [],
  loading: false,
  error: null
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchCityForecast = createAsyncThunk(
  'fetchCityForecast',
  async (city) => {
      try{
        const response = await fetchCityWeather(city);
        return response.data;
      }catch(error){
        throw Error(error)
      }
  }
);


export const forecastSlice = createSlice({
    name: 'forecast',
    initialState,
    reducers: {
      
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(fetchCityForecast.pending, (state) => {
          state.loading = true;
          state.error = false;
        })
        .addCase(fetchCityForecast.rejected, (state, action) => {
            state.error = action.error.message
            state.loading = false;
        })
        .addCase(fetchCityForecast.fulfilled, (state, action) => {
          state.loading = false;
          state.error = false;
          state.forecasts.push(action.payload);
          console.log("Here's the state after fetching weather.")
          console.log(current(state))
        })
    },
});


export default forecastSlice.reducer;
